name: Sync Datasets

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Sync Script
        run: node sync.js
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          CURRENT_COMMIT: ${{ github.sha }}

      - name: Commit and Push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add -A

          commit_message="Updated on $(date -u +'%Y-%m-%d')"

          git diff --quiet && git diff --staged --quiet || git commit -m "$commit_message"

          git push